### ISSUE TITLE
teleTAN without positive test?

### ISSUE THREAD

**Issue by cfritzsche** [corona-warn-app/cwa-verification-portal#53]
The [README.MD](https://github.com/corona-warn-app/cwa-verification-portal/blob/master/README.md#about-this-component) says:
> In other words: For all People who are willing to join the tracing process, but have not been tested by one of the participating laboratories, there will be a service hotline one can call to get a temporary Transaction Authentication Number (TAN) to join the process. The agents at the service hotline will ask the caller some questions to verify his status and then provide one with a TAN.

To me that sounds as if teleTANs can be generated by hotline users without a positive test to aid the tracing process.

While I welcome this feature, I am confused as it was declared out of scope so far in [cwa-documentation](https://github.com/corona-warn-app/cwa-documentation/issues/16#issuecomment-628073288).

If this is part of the first release, great! Will the teleTAN without test be of a separate kind as other teleTANs? If yes, that process is missing in the [solution architecture document](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#retrieval-of-lab-results-and-verification-process). If not, how would a second-degree contact be able to differentiate between a real exposure notification and a notification for contact tracing with confirmed test?

If this paragraph does not talk about teleTANs before positive test or second-degree contact tracing, what else does it mean?

**Comment by ascheibal** [comment]
Hi @cfritzsche,
the teleTan indeed shall only be offered to persons who have been tested positive, but do not have a QR-Code with the GUID like in the process with participating labratories. As further laboratories still get included in the process, it is also an interims solution for people, tested by such laboratories.
