### ISSUE TITLE
Codespell report for "cwa-verification-portal" (on fossies.org)

### ISSUE THREAD

**Issue by jschleus** [corona-warn-app/cwa-verification-portal#62]
Similar to the description in the issue [cwa-app-ios#149](https://github.com/corona-warn-app/cwa-app-ios/issues/149) there exists on [fossies.org](https://fossies.org) also a regularly updated [codespell](https://github.com/codespell-project/codespell) [report](https://fossies.org/features.html#codespell) for "cwa-verification-portal":

&nbsp;&nbsp;https://fossies.org/linux/test/cwa-verification-portal-master.tar.gz/codespell.html

**Comment by daniel-eder** [comment]
This is a good first issue. No programming experience is required, this issue is only about fixing typos as listed here: https://fossies.org/linux/test/cwa-verification-portal-master.tar.gz/codespell.html

Despite the simplicity, we appreciate any contributions!

**Comment by dfischer-tech** [comment]
Currnently the portal contains no spelling errors.
