### ISSUE TITLE
Security Risk : teleTan-Creation needs to be logged with hotline agent name

### ISSUE THREAD

**Issue by HolgerMayer** [corona-warn-app/cwa-verification-portal#69]
## Describe the bug

Security risks from inside an organisation are often underestimated. Let's see how this may be a problem for the Corona app.

Quote from https://www.chip.de/news/Corona-App-steht-kurz-vor-dem-Start-Scheitert-das-Warn-Tool-an-einem-einfachen-Problem_182639402.html
_

> Knapp 1.000 Anrufe soll die Hotline pro Tag bewältigen können. Nach Spiegel-Informationen sollen bereits Probeläufe gezeigt haben, dass das System funktioniert. Das Call-Center betreibt ein externen Dienstleister. Ob dieser in Deutschland sitzt, ist unklar.

_

A hotline agent currently is a trusted person who may create teleTans. Problem : is it correct to trust him if one even doesn't know if he works in Germany, Croatia, India or even a prison in the US?

Currently a hotline agent can create teleTans without the knowledge of a supervisor. It is not even possible to trace who created which teleTan.

## Expected behaviour

It is easy to create teleTans that could be misused. Don't ask for a misuse scenario  - as long as it is possible there will be an invalid use.

## Possible Fix

Log teleTan creation with hotline agent id and date/time.

See also  CWA_Documentation issue #129

**Comment by HolgerMayer** [comment]
After reading „Der Bericht der Datenschutz-Folgenabschätzung für die Corona-Warnapp“ I will not use the Corona warn app. According to this report it is necessary to leave my phone number and name at the hotline. A hotline I know nothing about. Not where it is. Not who runs it. This is a major problem of your requirements. The outer borders of the system are  defined too narrow.

There is no guarantee the data are destroyed after an hour. We know other cases where confidential data was found besides roadways.

**Comment by Ein-Tim** [comment]
**After I finished my investigation, I saw that is only partly related to the real "bug" described here, however, maybe it helps:**


I did some quick investigation.

The page https://www.telekom.com/de/konzern/themenspecials/special-corona/special-corona-warn-app shows in the second "slide" this picture: 
<img width="1032" alt="AXIVAS" src="https://user-images.githubusercontent.com/67682506/113327853-bd0bcf80-931b-11eb-86d9-1fee17a8f822.png">

There's a logo which says "AXIVAS". The first result on a [google search](https://www.google.com/search?q=AXIVAS&client=safari&source=hp&ei=FftlYP3iFfH1qwG9j5rgDw&iflsig=AINFCbYAAAAAYGYJJfqdvmxu7LpgwKoWmHAdIwzyDms-&oq=AXIVAS&gs_lcp=Cgdnd3Mtd2l6EAMyCAgAEMcBEK8BMgIIADICCAAyAggAMggIABDHARCvATICCAAyAggAMgIIADICCAAyAggAOgUIABCLAzoLCAAQxwEQowIQiwM6CAgAEMcBEKMCOgUILhCTAjoFCC4QiwM6CwgAEMcBEK8BEIsDOgQIABAKUO8JWPQQYPUSaABwAHgAgAGdA4gBsgaSAQU1LjQtMZgBAKABAaoBB2d3cy13aXq4AQI&sclient=gws-wiz&ved=0ahUKEwi9werTwd3vAhXx-ioKHb2HBvwQ4dUDCAw&uact=5) is https://alex-gross.com. 

The [contract](https://fragdenstaat.de/dokumente/7254-smfc-b-fs-020072417290/) between the federal government and Deutsche Telekom also mentions "Axivas" under point 7;
"Axivas Deutschland GmbH - Call-Center-Dienstleistungen".

The same contract, on page 93 (counting from fragdenstaat.de - on the paper it's page 19 out of 25), says under point  3 "Verarbeitungsort":

"Die Verarbeitung der Daten findet in Deutschland, den Niederlanden und Ungarn statt. [...]"


And, now what has been asked here:

Annex 4, on page 97 (paper: 23 out of 25) says to the Axivas GmbH:

"Verarbeitungsort Deutschland".

So, the verification hotline, if I understand everything correct, is operated by the "Axivas GmbH" in Germany.
