### ISSUE TITLE
Processes should not be run as root inside docker containers

### ISSUE THREAD

**Issue by mscheffel** [corona-warn-app/cwa-verification-portal#80]
It is advised by the docker community to not run processes inside a docker container as root, as it may give additional freedom to a successful attacker.

The dockerfiles listed should change the executing user to something else than root especially the one running mvn:

https://github.com/corona-warn-app/cwa-verification-portal/blob/master/Dockerfile
https://github.com/corona-warn-app/cwa-verification-portal/blob/master/DockerfilePaaS

**Comment by mscheffel** [comment]
Same at:
https://github.com/corona-warn-app/cwa-testresult-server/blob/master/Dockerfile
https://github.com/corona-warn-app/cwa-testresult-server/blob/master/DockerfilePaaS

Is it ok to collect this inside this issue or should I open another issue in cwa-testresult-server?
Thank you in advance!

**Comment by BugBuster1701** [comment]
cwa-verification-server: https://github.com/corona-warn-app/cwa-verification-server/pull/173
cwa-verfication-portal: https://github.com/corona-warn-app/cwa-verification-portal/pull/85

**Comment by mscheffel** [comment]
Hi guys - still ongoing? :-D

**Comment by ascheibal** [comment]
Hi @mscheffel. Thanks for that, we already did this in other verification repos, but obviously missed this one.
Your contribution is very appreciated.
