### ISSUE TITLE
bug: JWT Token does not work on WRU

### ISSUE THREAD

**Issue by paszimme** [corona-warn-app/cwa-verification-portal#90]
## Problem description
TeleTan Portal for WRU works unstable, generating new teletan is unresponsive and leads to error message that 'due to internal error, new teletan cannot be generated'

Error messages appear
Time limitations appear
See attached pictures

 
#### Link to Tester's Jira
https://jira.itc.sap.com/projects/EXPOSUREAPP/issues/EXPOSUREAPP-1680

**Comment by ascheibal** [comment]
Due to JWT not working properly on WRU, communication between cwa-verification-portal, cwa-verification-iam and cwa-verification-server runs into timeouts.
