### ISSUE TITLE
I need api-ul api- For face. FaceTime

### ISSUE THREAD

**Issue by lobsterlooks** [corona-warn-app/cwa-verification-portal#98]
I need an api -ul api for FaceTime live broadcasting ipa-ca wak-code .,/code/htlm.’__c broadcasting  ! ,ecc’em/.v vi

**Comment by Ein-Tim** [comment]
I think we can close this, or are we now developing a FaceTime API? 😂
(cc @daniel-eder)

**Comment by daniel-eder** [comment]
@Ein-Tim thanks .. not sure where that came from!
