### ISSUE TITLE
weitere Gesundheitsämter anbinden

### ISSUE THREAD

**Issue by paszimme** [corona-warn-app/cwa-verification-portal#99]

**Comment by Ein-Tim** [comment]
@paszimme 

If this is still a valid issue I suggest that you close it here and open a new one with a bit more details in the https://github.com/corona-warn-app/cwa-wishlist repository.

**Comment by daniel-eder** [comment]
@Ein-Tim This is actually an issue we opened internally for the backlog - it's unlikely that there will be more movement, but it can remain for now.
